### ISSUE TITLE
Error on startup on the Mac (InteractionServerBootProcedure)

### ISSUE THREAD

**Issue by smithmx** [dolittle-runtime/Runtime#256]
Application startup exception: Autofac.Core.DependencyResolutionException: An exception was thrown while activating Dolittle.Runtime.Server.InteractionServerBootProcedure -> Dolittle.Runtime.Server.InteractionServer. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Dolittle.Types.IInstancesOf`1[Dolittle.Runtime.Server.ICanBindInteractionServices], Dolittle.Runtime.Server.Configuration, Dolittle.Logging.ILogger)' on type 'InteractionServer'. ---> System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Dolittle.Runtime.Server.InteractionServer.CreateServer()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Dolittle.Types.InstancesOf`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Dolittle.Booting.BootProcedures.Perform()
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseDolittle(IApplicationBuilder app)
   at Core.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/Startup.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Dolittle.Runtime.Server.InteractionServerBootProcedure -> Dolittle.Runtime.Server.InteractionServer. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Dolittle.Types.IInstancesOf`1[Dolittle.Runtime.Server.ICanBindInteractionServices], Dolittle.Runtime.Server.Configuration, Dolittle.Logging.ILogger)' on type 'InteractionServer'. ---> System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Dolittle.Runtime.Server.InteractionServer.CreateServer()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext contex
t, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.CoreUnhandled Exception: .Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Dolittle.Types.InstancesOf`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Dolittle.Booting.BootProcedures.Perform()
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseDolittle(IApplicationBuilder app)
   at Core.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/Startup.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Dolittle.Runtime.Server.InteractionServerBootProcedure -> Dolittle.Runtime.Server.InteractionServer. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Dolittle.Types.IInstancesOf`1[Dolittle.Runtime.Server.ICanBindInteractionServices], Dolittle.Runtime.Server.Configuration, Dolittle.Logging.ILogger)' on type 'InteractionServer'. ---> System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/bin/Debug/netcoreapp2.2/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Dolittle.Runtime.Server.InteractionServer.CreateServer()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Dolittle.Types.InstancesOf`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Dolittle.Booting.BootProcedures.Perform()
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseDolittle(IApplicationBuilder app)
   at Core.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/Startup.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Core.Program.Main(String[] args) in /Users/michael/Documents/aksio/ProsjektLiv/Source/Pricing/Core/Program.cs:line 12

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1125712330263113)

**Comment by smithmx** [comment]
This occurs when you use the 

<CopyToOutputDirectory>Always</CopyToOutputDirectory>

in the .csproj file or 

dotnet build /p:CopyToOutputDirectory=true
